# Generated by Django 4.2.20 on 2025-05-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
