# Generated by Django 4.2.20 on 2025-05-07 14:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_home_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='side_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
