# Generated by Django 4.2.20 on 2025-05-14 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_category_options_alter_food_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['-category']},
        ),
    ]
