# Generated by Django 4.2.20 on 2025-05-15 13:36

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_food_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wanted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.AddIndex(
            model_name='wanted',
            index=models.Index(fields=['id'], name='menu_wanted_id_7ba65c_idx'),
        ),
        migrations.AddIndex(
            model_name='wanted',
            index=models.Index(fields=['name'], name='menu_wanted_name_9000d5_idx'),
        ),
    ]
