# Generated by Django 4.2.20 on 2025-05-17 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_wanted_remove_food_category_delete_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wanted',
            old_name='available',
            new_name='wanted',
        ),
    ]
